create table public.profile (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  auth_id uuid null,
  email text null,
  nome text null,
  role text null,
  constraint profile_pkey primary key (id),
  constraint profile_auth_id_fkey foreign KEY (auth_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create trigger on_profile_created
after INSERT on profile for EACH row
execute FUNCTION handle_profile_role ();