create table mentor_bookings (
  id bigint generated by default as identity primary key,
  aluno_id bigint,
  mentor_id bigint,
  weekday_id bigint,
  mentor_time_slot_id bigint,
  status text default 'reservado',
  video_link text,
  created_at timestamptz default now()
);
